- hosts: localhost
  tasks:
  - name: Check Docker API version
    command: "{{ ansible_python.executable }} -c 'import docker; print(docker.from_env().version()[\"ApiVersion\"])'"
    register: docker_api_version_stdout
    ignore_errors: yes

  - name: Check docker-py API version
    command: "{{ ansible_python.executable }} -c 'import docker; print(docker.__version__)'"
    register: docker_py_version_stdout
    ignore_errors: yes

  - set_fact:
      docker_api_version: "{{ docker_api_version_stdout.stdout or '0.0' }}"
      docker_py_version: "{{ docker_py_version_stdout.stdout or '0.0' }}"

  - debug:
      msg: "Docker API version: {{ docker_api_version }}; docker-py library version: {{ docker_py_version }}"

  - include_tasks: tasks/main.yml
    vars:
      role_path: '.'
